(*********************************************************************************)
(*  central - Manage history between sub-repos and their monorepo                *)
(*  SPDX-FileCopyrightText: 2024-2026 Mathieu Barbin <mathieu.barbin@gmail.com>  *)
(*  SPDX-License-Identifier: MIT                                                 *)
(*********************************************************************************)

(* Like [import.ml] and [push.ml], this page runs the real [central]
   executable (see [Central_test_harness]) rather than calling into
   [Central_cli]'s OCaml implementation directly - so what you read below is,
   command for command, what a [central] user would type and see in their own
   terminal. *)

(* @mdexp.config { snapshot: { lang: "ansi" } } *)

(* @mdexp

# Export

`central export <repo> -m MSG` moves changes made directly in `central`,
under `repo/<repo>/`, out into `<repo>`'s own standalone git repository - as
a single new commit on top of its `subrepo` branch.

It is the native-OCaml replacement for the one `git subrepo` command that
sits on `central`'s critical, day-to-day path: `git subrepo push`. Unlike
that command, `export` always squashes whatever changed since the last sync
into exactly one new commit, using the message supplied with `-m`.

Concretely, it:

1. Verifies the subrepo's `subrepo` branch has not moved since the last sync
   recorded in `repo/<repo>/.gitrepo` (if it has, someone likely pushed there
   directly - bring that in first before exporting).
2. Computes the diff of everything under `repo/<repo>/` since that sync,
   using `git diff --relative=`, which also strips the `repo/<repo>/` path
   prefix from the patch.
3. Applies that patch as one commit onto the subrepo's `subrepo` branch, via
   `git apply --3way --index`.
4. Updates `.gitrepo` in `central` to record the new sync point.

## A fake repo to work with

This walkthrough uses `Central_test_helpers` to build a fake `central`
repo with a made-up subrepo, `widget`, and a fake standalone repo standing
in for `widget`'s own history, wired together with a `.gitrepo` file
exactly as `central subrepo init` would leave them.

Right after that, `repo/widget/README.md` in `central` and `widget`'s own
`README.md` are identical: *)

let%expect_test "before" =
  let vcs = Volgo_git_unix.create () in
  let widget = Central.Subrepo.v "widget" in
  let fake_central = Central_test_helpers.create ~vcs ~subrepos:[ widget ] in
  let { Central_test_helpers.Fake_central.central_root; _ } = fake_central in
  Central_test_helpers.print_file
    ~repo_root:central_root
    ~path_in_repo:(Vcs.Path_in_repo.v "repo/widget/README.md");
  (* @mdexp.snapshot { lang: "markdown" } *)
  [%expect
    {|
    # widget

    This is a fake [widget] repo, generated by [Central_test_helpers] for tests.
    |}]
;;

(* @mdexp

## Editing directly in central, then exporting

Suppose someone edits `repo/widget/README.md` directly from within `central`
and commits it there - the way most day-to-day changes happen. Running
`export` then brings that change out, as a single new commit on top of
`widget`'s `subrepo` branch: *)

let%expect_test "edit and export" =
  let vcs = Volgo_git_unix.create () in
  let widget = Central.Subrepo.v "widget" in
  let fake_central = Central_test_helpers.create ~vcs ~subrepos:[ widget ] in
  let { Central_test_helpers.Fake_central.central_root; _ } = fake_central in
  let fake_widget =
    Central_test_helpers.Fake_central.find_exn fake_central ~subrepo:widget
  in
  let readme_path = Vcs.Path_in_repo.v "repo/widget/README.md" in
  Central_test_helpers.append_file
    ~repo_root:central_root
    ~path_in_repo:readme_path
    ~text:"\nAdded a line about installation.\n";
  Vcs.add vcs ~repo_root:central_root ~path:readme_path;
  let (_ : Vcs.Rev.t) =
    Central_test_helpers.commit
      ~vcs
      ~repo_root:central_root
      ~commit_message:"Document installation in widget's README"
  in
  let harness = Central_test_harness.create ~repo_root:central_root in
  let@ central = Central_test_harness.with_cli harness ~cwd:central_root in
  central [ [ "export"; "widget" ]; [ "-m"; "Document installation" ] ];
  (* @mdexp.snapshot *)
  [%expect
    {|
    $ central export widget -m "Document installation"
    ==================== widget ====================
    [ OK ] Applied patch in the subrepo.
    [ OK ] Exported to [widget].
    |}];
  (* @mdexp

     It landed in `widget`'s own history as one new commit on the `subrepo`
     branch, carrying exactly that change: *)
  Central_test_helpers.print_log_subjects
    ~vcs
    ~repo_root:fake_widget.repo_root
    ~ref_:"subrepo"
    ();
  (* @mdexp.snapshot *)
  [%expect
    {|
    Document installation
    Initial commit
    |}];
  Central_test_helpers.print_file
    ~repo_root:fake_widget.repo_root
    ~path_in_repo:(Vcs.Path_in_repo.v "README.md");
  (* @mdexp.snapshot { lang: "markdown" } *)
  [%expect
    {|
    # widget

    This is a fake [widget] repo, generated by [Central_test_helpers] for tests.

    Added a line about installation.
    |}]
;;

(* @mdexp

## Guardrails

Running `export` again right away, with nothing new to export, is a clean
error rather than an empty commit: *)

let%expect_test "nothing to export" =
  let vcs = Volgo_git_unix.create () in
  let widget = Central.Subrepo.v "widget" in
  let fake_central = Central_test_helpers.create ~vcs ~subrepos:[ widget ] in
  let { Central_test_helpers.Fake_central.central_root; _ } = fake_central in
  let harness = Central_test_harness.create ~repo_root:central_root in
  let@ central = Central_test_harness.with_cli harness ~cwd:central_root in
  central [ [ "export"; "widget" ]; [ "-m"; "Nothing changed" ] ];
  (* @mdexp.snapshot *)
  [%expect
    {|
    $ central export widget -m "Nothing changed"
    ==================== widget ====================
    Error: Nothing to export: no changes under "repo/widget" since the last sync.
    [123]
    |}]
;;

(* @mdexp

And if the subrepo's `subrepo` branch moved since the last sync - for
example because someone pushed to it directly, bypassing `central` - `export`
refuses rather than silently basing the new commit on the wrong parent: *)

let%expect_test "branch moved" =
  let vcs = Volgo_git_unix.create () in
  let widget = Central.Subrepo.v "widget" in
  let fake_central = Central_test_helpers.create ~vcs ~subrepos:[ widget ] in
  let { Central_test_helpers.Fake_central.central_root; _ } = fake_central in
  let fake_widget =
    Central_test_helpers.Fake_central.find_exn fake_central ~subrepo:widget
  in
  let readme = Vcs.Path_in_repo.v "README.md" in
  Vcs.git
    vcs
    ~repo_root:fake_widget.repo_root
    ~args:[ "checkout"; "subrepo" ]
    ~f:Vcs.Git.exit0;
  Central_test_helpers.append_file
    ~repo_root:fake_widget.repo_root
    ~path_in_repo:readme
    ~text:"\nEdited directly upstream.\n";
  Vcs.add vcs ~repo_root:fake_widget.repo_root ~path:readme;
  let (_ : Vcs.Rev.t) =
    Central_test_helpers.commit
      ~vcs
      ~repo_root:fake_widget.repo_root
      ~commit_message:"Edited directly upstream"
  in
  let harness = Central_test_harness.create ~repo_root:central_root in
  let@ central = Central_test_harness.with_cli harness ~cwd:central_root in
  central [ [ "export"; "widget" ]; [ "-m"; "Should not apply" ] ];
  (* @mdexp.snapshot *)
  [%expect
    {|
    $ central export widget -m "Should not apply"
    ==================== widget ====================
    Error: The [subrepo] branch of [widget] has moved since the last sync
    recorded in [.gitrepo].
    Hint: Bring those changes into central first with [central import] before
    exporting, or pass [--force] to export anyway.
    [123]
    |}]
;;

(* @mdexp

And as a precondition, `export` first checks that `central`'s own working
tree is clean - an unstaged edit is rejected outright, before anything else
is even looked at: *)

let%expect_test "dirty working tree" =
  let vcs = Volgo_git_unix.create () in
  let widget = Central.Subrepo.v "widget" in
  let fake_central = Central_test_helpers.create ~vcs ~subrepos:[ widget ] in
  let { Central_test_helpers.Fake_central.central_root; _ } = fake_central in
  (* Edited, but never [Vcs.add]ed - left unstaged. *)
  Central_test_helpers.append_file
    ~repo_root:central_root
    ~path_in_repo:(Vcs.Path_in_repo.v "repo/widget/README.md")
    ~text:"\nStray, unstaged edit.\n";
  let harness = Central_test_harness.create ~repo_root:central_root in
  let@ central = Central_test_harness.with_cli harness ~cwd:central_root in
  central [ [ "export"; "widget" ]; [ "-m"; "Should not apply" ] ];
  (* @mdexp.snapshot *)
  [%expect
    {|
    $ central export widget -m "Should not apply"
    ==================== widget ====================
    Error: Repo "$CENTRAL_ROOT" has uncommitted changes -
    commit or stash them first.
    Hint: M repo/widget/README.md
    [123]
    |}]
;;

(* @mdexp

## Exporting several subrepos at once

Chores that make the same systematic change across many subrepos are common
enough that `export` accepts more than one `REPO` at a time (or `--all` for
every subrepo it knows about) - each is exported in turn, in the order
given, with a separator banner between them, reusing the same `-m` message
for every commit: *)

let%expect_test "export several subrepos at once" =
  let vcs = Volgo_git_unix.create () in
  let widget = Central.Subrepo.v "widget" in
  let gadget = Central.Subrepo.v "gadget" in
  let fake_central = Central_test_helpers.create ~vcs ~subrepos:[ widget; gadget ] in
  let { Central_test_helpers.Fake_central.central_root; _ } = fake_central in
  let fake_widget =
    Central_test_helpers.Fake_central.find_exn fake_central ~subrepo:widget
  in
  let fake_gadget =
    Central_test_helpers.Fake_central.find_exn fake_central ~subrepo:gadget
  in
  List.iter [ widget; gadget ] ~f:(fun subrepo ->
    let path_in_repo =
      Vcs.Path_in_repo.v
        (Printf.sprintf "repo/%s/README.md" (Central.Subrepo.to_string subrepo))
    in
    Central_test_helpers.append_file
      ~repo_root:central_root
      ~path_in_repo
      ~text:"\nSee LICENSE for details.\n";
    Vcs.add vcs ~repo_root:central_root ~path:path_in_repo);
  let (_ : Vcs.Rev.t) =
    Central_test_helpers.commit
      ~vcs
      ~repo_root:central_root
      ~commit_message:"Add license footer to every subrepo"
  in
  let harness = Central_test_harness.create ~repo_root:central_root in
  let@ central = Central_test_harness.with_cli harness ~cwd:central_root in
  central [ [ "export"; "widget"; "gadget" ]; [ "-m"; "Add license footer" ] ];
  (* @mdexp.snapshot *)
  [%expect
    {|
    $ central export widget gadget -m "Add license footer"
    ==================== widget ====================
    [ OK ] Applied patch in the subrepo.
    [ OK ] Exported to [widget].
    ==================== gadget ====================
    [ OK ] Applied patch in the subrepo.
    [ OK ] Exported to [gadget].
    |}];
  (* @mdexp Both landed the same commit message on their own `subrepo` branch: *)
  List.iter
    [ fake_widget; fake_gadget ]
    ~f:(fun (fake_subrepo : Central_test_helpers.Fake_subrepo.t) ->
      Printf.printf "-- %s --\n" (Central.Subrepo.to_string fake_subrepo.subrepo);
      Central_test_helpers.print_log_subjects
        ~vcs
        ~repo_root:fake_subrepo.repo_root
        ~ref_:"subrepo"
        ();
      print_newline ());
  (* @mdexp.snapshot *)
  [%expect
    {|
    -- widget --
    Add license footer
    Initial commit
    -- gadget --
    Add license footer
    Initial commit
    |}];
  (* @mdexp

     `central todo` picks up both subrepos as done - since `export` doesn't
     touch `central`'s own history, both are shown ready for their next
     step, `advance-main`, while `central` itself needs a `push` for the
     `.gitrepo` updates: *)
  central [ [ "todo" ] ];
  (* @mdexp.snapshot *)
  [%expect
    {|
    $ central todo
    ┌──────────┬──────────────┬──────┐
    │ Repo     │ Next step    │ Diff │
    ├──────────┼──────────────┼──────┤
    │ central  │ push         │   12 │
    │   gadget │ advance-main │      │
    │   widget │ advance-main │      │
    └──────────┴──────────────┴──────┘
    |}]
;;

(* @mdexp

`export` stops at the first repo that fails, leaving the ones after it in
the list untouched - it doesn't try to skip ahead and report a summary at
the end. Say `gadget`'s `subrepo` branch moved independently in the
meantime (someone pushed to it directly, bypassing central) while `widget`
is perfectly exportable: *)

let%expect_test "stops at the first repo that fails" =
  let vcs = Volgo_git_unix.create () in
  let widget = Central.Subrepo.v "widget" in
  let gadget = Central.Subrepo.v "gadget" in
  let fake_central = Central_test_helpers.create ~vcs ~subrepos:[ widget; gadget ] in
  let { Central_test_helpers.Fake_central.central_root; _ } = fake_central in
  let fake_gadget =
    Central_test_helpers.Fake_central.find_exn fake_central ~subrepo:gadget
  in
  let widget_readme = Vcs.Path_in_repo.v "repo/widget/README.md" in
  Central_test_helpers.append_file
    ~repo_root:central_root
    ~path_in_repo:widget_readme
    ~text:"\nSee LICENSE for details.\n";
  Vcs.add vcs ~repo_root:central_root ~path:widget_readme;
  let (_ : Vcs.Rev.t) =
    Central_test_helpers.commit
      ~vcs
      ~repo_root:central_root
      ~commit_message:"Add license footer to widget"
  in
  (* [gadget]'s own history moved on its own, bypassing central entirely. *)
  let readme = Vcs.Path_in_repo.v "README.md" in
  Vcs.git
    vcs
    ~repo_root:fake_gadget.repo_root
    ~args:[ "checkout"; "subrepo" ]
    ~f:Vcs.Git.exit0;
  Central_test_helpers.append_file
    ~repo_root:fake_gadget.repo_root
    ~path_in_repo:readme
    ~text:"\nEdited directly upstream.\n";
  Vcs.add vcs ~repo_root:fake_gadget.repo_root ~path:readme;
  let (_ : Vcs.Rev.t) =
    Central_test_helpers.commit
      ~vcs
      ~repo_root:fake_gadget.repo_root
      ~commit_message:"Edited directly upstream"
  in
  let harness = Central_test_harness.create ~repo_root:central_root in
  let@ central = Central_test_harness.with_cli harness ~cwd:central_root in
  central [ [ "export"; "widget"; "gadget" ]; [ "-m"; "Add license footer" ] ];
  (* @mdexp.snapshot *)
  [%expect
    {|
    $ central export widget gadget -m "Add license footer"
    ==================== widget ====================
    [ OK ] Applied patch in the subrepo.
    [ OK ] Exported to [widget].
    ==================== gadget ====================
    Error: The [subrepo] branch of [gadget] has moved since the last sync
    recorded in [.gitrepo].
    Hint: Bring those changes into central first with [central import] before
    exporting, or pass [--force] to export anyway.
    [123]
    |}]
;;
