(*********************************************************************************)
(*  central - Manage history between sub-repos and their monorepo                *)
(*  SPDX-FileCopyrightText: 2024-2026 Mathieu Barbin <mathieu.barbin@gmail.com>  *)
(*  SPDX-License-Identifier: MIT                                                 *)
(*********************************************************************************)

(* Like [export.ml], this runs the real [central] executable (see
   [Central_test_harness]) rather than calling into the CLI's OCaml
   implementation directly. *)

(* @mdexp.config { snapshot: { lang: "ansi" } } *)

(* @mdexp

# Import

`central import <repo>` brings commits from the tip of the subrepo's
`subrepo` branch - normally landed there by fetching from the subrepo's real
remote - into `repo/REPO`. `-m MSG` is optional and defaults to `"Import
changes from REPO"`.

Unlike `export`, this has to account for central having moved on since the
last sync - so it picks between two ways of bringing the change in,
depending on whether central has any local changes of its own under
`repo/REPO`:

- If central hasn't touched `repo/REPO` at all since the last sync,
  `repo/REPO` at central's current HEAD is - by construction - exactly what
  it was at the last sync point, so the subrepo's diff is guaranteed to
  apply there too. There is nothing to merge, so `import` doesn't build
  one: it applies the diff directly as a single new commit on top of HEAD.
  This is the default, and it keeps history linear in the common case where
  central had no reason to conflict with what the subrepo brings in.
- Otherwise - central *does* have local changes of its own under
  `repo/REPO` - `import` falls back to an ordinary two-parent `git merge`:
  it builds a new commit as a direct child of the central revision recorded
  in `repo/REPO/.gitrepo` - not of the current HEAD - and applies the
  subrepo's diff there, where it is guaranteed to apply cleanly regardless
  of what else happened on central's actual HEAD since. That commit (the
  "import commit") also updates `.gitrepo` to record the new sync point.
  Merging it into the active branch is then an ordinary `git merge`: if
  there is a real conflict, git surfaces it exactly as it always does, for
  a human to resolve.

## Applying directly

A fake `central` and a fake `widget`, as usual - someone pushes directly to
`widget`'s `subrepo` branch (standing in for something fetched from its
real remote), while central hasn't touched `repo/widget/` since the last
sync. So `import` applies the upstream change straight onto HEAD, no merge
needed: *)

let%expect_test "direct import (central has no local changes)" =
  let vcs = Volgo_git_unix.create () in
  let widget = Central.Subrepo.v "widget" in
  let fake_central = Central_test_helpers.create ~vcs ~subrepos:[ widget ] in
  let { Central_test_helpers.Fake_central.central_root; _ } = fake_central in
  let fake_widget =
    Central_test_helpers.Fake_central.find_exn fake_central ~subrepo:widget
  in
  (* Someone pushes directly to the [subrepo] branch, bypassing central. *)
  let readme = Vcs.Path_in_repo.v "README.md" in
  Vcs.git
    vcs
    ~repo_root:fake_widget.repo_root
    ~args:[ "checkout"; "subrepo" ]
    ~f:Vcs.Git.exit0;
  Central_test_helpers.append_file
    ~repo_root:fake_widget.repo_root
    ~path_in_repo:readme
    ~text:"\nEdited directly upstream.\n";
  Vcs.add vcs ~repo_root:fake_widget.repo_root ~path:readme;
  let (_ : Vcs.Rev.t) =
    Central_test_helpers.commit
      ~vcs
      ~repo_root:fake_widget.repo_root
      ~commit_message:"Edited directly upstream"
  in
  let harness = Central_test_harness.create ~repo_root:central_root in
  let@ central = Central_test_harness.with_cli harness ~cwd:central_root in
  central [ [ "import"; "widget" ] ];
  (* @mdexp.snapshot *)
  [%expect
    {|
    $ central import widget
    [ OK ] Imported into [main] directly (no merge needed).
    |}];
  (* @mdexp

     A single, linear commit lands directly on top of HEAD - no second
     parent, no merge commit. `-m` was left out here, so the message falls
     back to `"Import changes from widget"`: *)
  Central_test_helpers.print_log_subjects ~vcs ~repo_root:central_root ~ref_:"main" ();
  (* @mdexp.snapshot *)
  [%expect
    {|
    Import changes from widget
    Add fake subrepo widget
    Initial commit
    |}];
  Central_test_helpers.print_file
    ~repo_root:central_root
    ~path_in_repo:(Vcs.Path_in_repo.v "repo/widget/README.md");
  (* @mdexp.snapshot { lang: "markdown" } *)
  [%expect
    {|
    # widget

    This is a fake [widget] repo, generated by [Central_test_helpers] for tests.

    Edited directly upstream.
    |}]
;;

(* @mdexp

## Guardrails

Running `import` again right away, with nothing new upstream, is a clean
error rather than an empty commit - symmetric to `export`'s own guard: *)

let%expect_test "nothing to import" =
  let vcs = Volgo_git_unix.create () in
  let widget = Central.Subrepo.v "widget" in
  let fake_central = Central_test_helpers.create ~vcs ~subrepos:[ widget ] in
  let { Central_test_helpers.Fake_central.central_root; _ } = fake_central in
  let harness = Central_test_harness.create ~repo_root:central_root in
  let@ central = Central_test_harness.with_cli harness ~cwd:central_root in
  central [ [ "import"; "widget" ] ];
  (* @mdexp.snapshot *)
  [%expect
    {|
    $ central import widget
    Error: Nothing to import: the [subrepo] branch of [widget] has not moved
    since the last sync.
    [123]
    |}]
;;

(* @mdexp

And just like `export`, `import` first checks that `central`'s own working
tree is clean - an unstaged edit is rejected outright: *)

let%expect_test "dirty working tree" =
  let vcs = Volgo_git_unix.create () in
  let widget = Central.Subrepo.v "widget" in
  let fake_central = Central_test_helpers.create ~vcs ~subrepos:[ widget ] in
  let { Central_test_helpers.Fake_central.central_root; _ } = fake_central in
  (* Edited, but never [Vcs.add]ed - left unstaged. *)
  Central_test_helpers.append_file
    ~repo_root:central_root
    ~path_in_repo:(Vcs.Path_in_repo.v "README.md")
    ~text:"\nStray, unstaged edit.\n";
  let harness = Central_test_harness.create ~repo_root:central_root in
  let@ central = Central_test_harness.with_cli harness ~cwd:central_root in
  central [ [ "import"; "widget" ] ];
  (* @mdexp.snapshot *)
  [%expect
    {|
    $ central import widget
    Error: Repo "$CENTRAL_ROOT" has uncommitted changes -
    commit or stash them first.
    Hint: M README.md
    [123]
    |}]
;;

(* @mdexp

## Falling back to a merge

This time, central *does* touch something under `repo/widget/` since the
last sync - a new file of its own, `NOTES.md`, unrelated to the file
upstream changed. `import` can no longer assume `repo/widget/` is
untouched, so it falls back to building an import commit as a child of the
last sync point and merging it in. Since the two sides touch different
files, the merge still completes cleanly on its own: *)

let%expect_test "import with merge (central has local changes too)" =
  let vcs = Volgo_git_unix.create () in
  let widget = Central.Subrepo.v "widget" in
  let fake_central = Central_test_helpers.create ~vcs ~subrepos:[ widget ] in
  let { Central_test_helpers.Fake_central.central_root; _ } = fake_central in
  let fake_widget =
    Central_test_helpers.Fake_central.find_exn fake_central ~subrepo:widget
  in
  (* Someone pushes directly to the [subrepo] branch, bypassing central. *)
  let subrepo_readme = Vcs.Path_in_repo.v "README.md" in
  Vcs.git
    vcs
    ~repo_root:fake_widget.repo_root
    ~args:[ "checkout"; "subrepo" ]
    ~f:Vcs.Git.exit0;
  Central_test_helpers.append_file
    ~repo_root:fake_widget.repo_root
    ~path_in_repo:subrepo_readme
    ~text:"\nEdited directly upstream.\n";
  Vcs.add vcs ~repo_root:fake_widget.repo_root ~path:subrepo_readme;
  let (_ : Vcs.Rev.t) =
    Central_test_helpers.commit
      ~vcs
      ~repo_root:fake_widget.repo_root
      ~commit_message:"Edited directly upstream"
  in
  (* Meanwhile, central also gets its own, unrelated change under
     [repo/widget/] - a new file, so it cannot conflict textually with the
     incoming change, but it does mean central has changes of its own since
     the last sync, forcing the merge path. *)
  let notes_path = Vcs.Path_in_repo.v "repo/widget/NOTES.md" in
  Central_test_helpers.write_file
    ~repo_root:central_root
    ~path_in_repo:notes_path
    ~contents:"Some local notes.\n";
  Vcs.add vcs ~repo_root:central_root ~path:notes_path;
  let (_ : Vcs.Rev.t) =
    Central_test_helpers.commit
      ~vcs
      ~repo_root:central_root
      ~commit_message:"Add local notes under widget"
  in
  let harness = Central_test_harness.create ~repo_root:central_root in
  let@ central = Central_test_harness.with_cli harness ~cwd:central_root in
  central [ [ "import"; "widget" ] ];
  (* @mdexp.snapshot *)
  [%expect
    {|
    $ central import widget
    [ OK ] Built the import commit.
    Merge made by the 'ort' strategy.
     repo/widget/.gitrepo  | 4 ++--
     repo/widget/README.md | 2 ++
     2 files changed, 4 insertions(+), 2 deletions(-)
    [ OK ] Imported into [main].
    |}];
  (* @mdexp

     Unlike the direct case above, the import commit sits as a child of the
     *old* sync point, not of central's HEAD at the time - a separate line
     of history, joined by the merge: *)
  Central_test_helpers.print_log_subjects
    ~vcs
    ~repo_root:central_root
    ~ref_:"main"
    ~first_parent:true
    ();
  (* @mdexp.snapshot *)
  [%expect
    {|
    Merge widget import
    Add local notes under widget
    Add fake subrepo widget
    Initial commit
    |}]
;;

(* @mdexp

## A real conflict

Same fallback, but this time central and the subrepo both edit the very
same line under `repo/widget/` since the last sync: *)

let%expect_test "conflict" =
  let vcs = Volgo_git_unix.create () in
  let widget = Central.Subrepo.v "widget" in
  let fake_central = Central_test_helpers.create ~vcs ~subrepos:[ widget ] in
  let { Central_test_helpers.Fake_central.central_root; _ } = fake_central in
  let fake_widget =
    Central_test_helpers.Fake_central.find_exn fake_central ~subrepo:widget
  in
  let central_readme = Vcs.Path_in_repo.v "repo/widget/README.md" in
  (* Central edits the first line of widget's README directly. *)
  Central_test_helpers.write_file
    ~repo_root:central_root
    ~path_in_repo:central_readme
    ~contents:"# widget, edited by central\n";
  Vcs.add vcs ~repo_root:central_root ~path:central_readme;
  let (_ : Vcs.Rev.t) =
    Central_test_helpers.commit
      ~vcs
      ~repo_root:central_root
      ~commit_message:"Central retitles the README"
  in
  (* Upstream edits the very same line, differently. *)
  let subrepo_readme = Vcs.Path_in_repo.v "README.md" in
  Vcs.git
    vcs
    ~repo_root:fake_widget.repo_root
    ~args:[ "checkout"; "subrepo" ]
    ~f:Vcs.Git.exit0;
  Central_test_helpers.write_file
    ~repo_root:fake_widget.repo_root
    ~path_in_repo:subrepo_readme
    ~contents:"# widget, retitled upstream\n";
  Vcs.add vcs ~repo_root:fake_widget.repo_root ~path:subrepo_readme;
  let (_ : Vcs.Rev.t) =
    Central_test_helpers.commit
      ~vcs
      ~repo_root:fake_widget.repo_root
      ~commit_message:"Upstream retitles the README"
  in
  let harness = Central_test_harness.create ~repo_root:central_root in
  let@ central = Central_test_harness.with_cli harness ~cwd:central_root in
  central [ [ "import"; "widget" ]; [ "-m"; "Bring in upstream retitle" ] ];
  (* @mdexp.snapshot *)
  [%expect
    {|
    $ central import widget -m "Bring in upstream retitle"
    [ OK ] Built the import commit.
    Auto-merging repo/widget/README.md
    CONFLICT (content): Merge conflict in repo/widget/README.md
    Automatic merge failed; fix conflicts and then commit the result.
    Error: Merge conflict while importing - resolve the conflicts above in
    [main], then [git add] the resolved files and [git commit] to finish the
    merge.
    Hint: .gitrepo has already been updated as part of the import commit being
    merged - no further action needed there once the merge is complete.
    [123]
    |}];
  (* @mdexp

     Central is left in the middle of the merge, exactly as an ordinary
     `git merge` would - conflict markers included, with the trailing
     revision on `>>>>>>>` naming the import commit, the side being merged
     in: *)
  let merge_head =
    Vcs.git
      vcs
      ~repo_root:central_root
      ~args:[ "rev-parse"; "MERGE_HEAD" ]
      ~f:(fun output -> Vcs.Git.exit0_and_stdout output |> String.strip |> Vcs.Rev.v)
  in
  Central_test_harness.register_rev harness ~rev:merge_head;
  print_string
    (Central_test_harness.redact
       harness
       (String.strip
          (Central_test_helpers.read_file
             ~repo_root:central_root
             ~path_in_repo:central_readme)));
  (* @mdexp.snapshot { lang: "text" } *)
  [%expect
    {|
    <<<<<<< HEAD
    # widget, edited by central
    =======
    # widget, retitled upstream
    >>>>>>> 1185512b92d612b25613f2e5b473e5231185512b
    |}];
  (* @mdexp

     Resolving it is the same as for any git merge conflict - pick a
     resolution, `git add`, `git commit`: *)
  Central_test_helpers.write_file
    ~repo_root:central_root
    ~path_in_repo:central_readme
    ~contents:"# widget, retitled (resolved)\n";
  Vcs.add vcs ~repo_root:central_root ~path:central_readme;
  let (_ : Vcs.Rev.t) =
    Central_test_helpers.commit
      ~vcs
      ~repo_root:central_root
      ~commit_message:"Resolve README retitle conflict"
  in
  Central_test_helpers.print_log_subjects
    ~vcs
    ~repo_root:central_root
    ~ref_:"main"
    ~first_parent:true
    ();
  (* @mdexp.snapshot *)
  [%expect
    {|
    Resolve README retitle conflict
    Central retitles the README
    Add fake subrepo widget
    Initial commit
    |}];
  (* @mdexp

     `.gitrepo` was already updated as part of the import commit, so
     `export` is available again right away - it carries the resolution
     itself out to `widget`, since that's what central's own history now
     disagrees with: *)
  central [ [ "export"; "widget" ]; [ "-m"; "Resolve conflicting retitle" ] ];
  (* @mdexp.snapshot *)
  [%expect
    {|
    $ central export widget -m "Resolve conflicting retitle"
    ==================== widget ====================
    [ OK ] Applied patch in the subrepo.
    [ OK ] Exported to [widget].
    |}];
  Central_test_helpers.print_log_subjects
    ~vcs
    ~repo_root:fake_widget.repo_root
    ~ref_:"subrepo"
    ();
  (* @mdexp.snapshot *)
  [%expect
    {|
    Resolve conflicting retitle
    Upstream retitles the README
    Initial commit
    |}]
;;
