(library
 (name central)
 (public_name central)
 (flags
  :standard
  -w
  +a-4-40-41-42-44-45-48-66
  -warn-error
  +a
  -open
  Pplumbing_err
  -open
  Central_stdlib
  -open
  Volgo)
 (libraries central_stdlib fpath loc pp pplumbing-err volgo xdg yojson)
 (instrumentation
  (backend bisect_ppx))
 (lint
  (pps ppx_js_style -allow-let-operators -check-doc-comments))
 (preprocess no_preprocessing))
