(data_only_dirs shared-theme)

(library
 (name central_introduction)
 (package central-tests)
 (inline_tests
  (deps central.exe))
 (flags
  :standard
  -w
  +a-4-40-41-42-44-45-48-66
  -warn-error
  +a
  -open
  Central_stdlib
  -open
  Volgo
  -open
  Central)
 (libraries
  central
  central_stdlib
  central_test_harness
  central_test_helpers
  volgo
  volgo-git-unix)
 (instrumentation
  (backend bisect_ppx))
 (lint
  (pps ppx_js_style -allow-let-operators -check-doc-comments))
 (preprocess
  (pps ppx_expect)))

(rule
 (copy %{bin:central} central.exe))

(rule
 (enabled_if %{bin-available:mdexp})
 (target export.md.gen)
 (deps export.ml)
 (action
  (with-stdout-to
   %{target}
   (run mdexp pp %{deps}))))

(rule
 (enabled_if %{bin-available:mdexp})
 (alias runtest)
 (action
  (diff export.md export.md.gen)))

(rule
 (enabled_if %{bin-available:mdexp})
 (target import.md.gen)
 (deps import.ml)
 (action
  (with-stdout-to
   %{target}
   (run mdexp pp %{deps}))))

(rule
 (enabled_if %{bin-available:mdexp})
 (alias runtest)
 (action
  (diff import.md import.md.gen)))

(rule
 (enabled_if %{bin-available:mdexp})
 (target stitch.md.gen)
 (deps stitch.ml)
 (action
  (with-stdout-to
   %{target}
   (run mdexp pp %{deps}))))

(rule
 (enabled_if %{bin-available:mdexp})
 (alias runtest)
 (action
  (diff stitch.md stitch.md.gen)))

(rule
 (enabled_if %{bin-available:mdexp})
 (target push.md.gen)
 (deps push.ml)
 (action
  (with-stdout-to
   %{target}
   (run mdexp pp %{deps}))))

(rule
 (enabled_if %{bin-available:mdexp})
 (alias runtest)
 (action
  (diff push.md push.md.gen)))
