(*********************************************************************************)
(*  central - Manage history between sub-repos and their monorepo                *)
(*  SPDX-FileCopyrightText: 2024-2026 Mathieu Barbin <mathieu.barbin@gmail.com>  *)
(*  SPDX-License-Identifier: MIT                                                 *)
(*********************************************************************************)

module Fake_subrepo = struct
  type t =
    { subrepo : Central.Subrepo.t
    ; repo_root : Vcs.Repo_root.t
    ; remote_root : Vcs.Repo_root.t
    ; initial_rev : Vcs.Rev.t
    }
end

module Fake_central = struct
  type t =
    { central_root : Vcs.Repo_root.t
    ; central_remote_root : Vcs.Repo_root.t
    ; subrepos : Fake_subrepo.t list
    }

  let find_exn t ~subrepo =
    match
      List.find_opt t.subrepos ~f:(fun (fake_subrepo : Fake_subrepo.t) ->
        Central.Subrepo.equal fake_subrepo.subrepo subrepo)
    with
    | Some fake_subrepo -> fake_subrepo
    | None ->
      Err.raise
        Pp.O.
          [ Pp.text "No fake subrepo was created for "
            ++ Pp_tty.id (module Central.Subrepo) subrepo
            ++ Pp.text "."
          ]
  ;;
end

let read_file ~repo_root ~path_in_repo =
  In_channel.with_open_bin
    (Vcs.Repo_root.append repo_root path_in_repo |> Absolute_path.to_string)
    In_channel.input_all
;;

let print_file ~repo_root ~path_in_repo =
  print_string (String.trim (read_file ~repo_root ~path_in_repo))
;;

let print_log_subjects ?(first_parent = false) ~vcs ~repo_root ~ref_ () =
  let args =
    List.concat
      [ [ "log"; "--format=%s" ]
      ; (if first_parent then [ "--first-parent" ] else [])
      ; [ ref_ ]
      ]
  in
  print_string (String.trim (Vcs.git vcs ~repo_root ~args ~f:Vcs.Git.exit0_and_stdout))
;;

let print_graph ~vcs ~repo_root ~refs =
  print_string
    (String.trim
       (Vcs.git
          vcs
          ~repo_root
          ~args:(List.concat [ [ "log"; "--graph"; "--format=%s" ]; refs ])
          ~f:Vcs.Git.exit0_and_stdout))
;;

let rec mkdir_p dir =
  if not (Sys.file_exists dir)
  then (
    mkdir_p (Filename.dirname dir);
    try Unix.mkdir dir 0o755 with
    | Unix.Unix_error (Unix.EEXIST, _, _) -> ())
;;

let write_file ~repo_root ~path_in_repo ~contents =
  let path = Vcs.Repo_root.append repo_root path_in_repo |> Absolute_path.to_string in
  mkdir_p (Filename.dirname path);
  Out_channel.with_open_bin path (fun oc -> Out_channel.output_string oc contents)
;;

let append_file ~repo_root ~path_in_repo ~text =
  let path = Vcs.Repo_root.append repo_root path_in_repo |> Absolute_path.to_string in
  Out_channel.with_open_gen [ Open_append; Open_binary ] 0o644 path (fun oc ->
    Out_channel.output_string oc text)
;;

let commit ~vcs ~repo_root ~commit_message =
  Vcs.commit vcs ~repo_root ~commit_message:(Vcs.Commit_message.v commit_message)
;;

(* The README's content is derived from the subrepo's name so that fake
   central and fake subrepo repos start off in sync, and so that failures are
   easy to attribute to a particular fake subrepo when several are created in
   the same test. *)
let fake_readme_contents subrepo =
  Printf.sprintf
    "# %s\n\nThis is a fake [%s] repo, generated by [Central_test_helpers] for tests.\n"
    (Central.Subrepo.to_string subrepo)
    (Central.Subrepo.to_string subrepo)
;;

(* [Filename.temp_dir] honors [$TMPDIR], which on macOS is itself a symlink
   (e.g. into [/var/folders/...], with [/var] a symlink to [/private/var]).
   [Unix.realpath] resolves that once, up front, so that this directory's
   path already matches what [Unix.getcwd ()] reports once something [chdir]
   s into it and calls back into it - macOS's [getcwd] returns the fully
   resolved path, so without this the same directory would print under two
   different-looking absolute paths depending on which of the two functions
   produced the string. *)
let temp_dir prefix = Filename.temp_dir prefix "" |> Unix.realpath |> Absolute_path.v

(* This takes care of setting the user config with dummy values, so that
   [Vcs.commit] can be used without depending on the ambient user config -
   isolating the test from the local machine's settings, and making things
   work in CI environments where no default user config exists. *)
let init_repo vcs ~prefix =
  let repo_root = Vcs.init vcs ~path:(temp_dir prefix) in
  Vcs.set_user_name vcs ~repo_root ~user_name:(Vcs.User_name.v "Test User");
  Vcs.set_user_email vcs ~repo_root ~user_email:(Vcs.User_email.v "test@example.com");
  repo_root
;;

(* Renaming the current branch to [main] right after the first commit keeps
   the fake repos deterministic regardless of the ambient [init.defaultBranch]
   git config. *)
let commit_and_ensure_main_branch vcs ~repo_root ~commit_message =
  let rev =
    Vcs.commit vcs ~repo_root ~commit_message:(Vcs.Commit_message.v commit_message)
  in
  Vcs.rename_current_branch vcs ~repo_root ~to_:Vcs.Branch_name.main;
  rev
;;

(* A bare repo in its own throwaway temporary directory - never to be
   confused with any real, production remote. Bare (as any real remote
   effectively is), so pushing [main] to it - even while [main] is checked
   out in the pushing repo - never runs into git's "refusing to update the
   current branch" guard. *)
let create_bare_remote vcs ~prefix =
  let remote_root = temp_dir (prefix ^ "-remote") |> Vcs.Repo_root.of_absolute_path in
  Vcs.git vcs ~repo_root:remote_root ~args:[ "init"; "--bare" ] ~f:Vcs.Git.exit0;
  remote_root
;;

(* Both [Subrepo_facts.compute] and a "next step"-style overview both require
   [main] to have remote-tracking information (as a real checkout would,
   tracking its [origin]). Rather than fake that tracking info, a real,
   separate bare repo is created and [main] is genuinely pushed to it - so a
   test can also exercise [push] itself and inspect what actually landed on
   the far end, not just whether [central] thinks a push is due. *)
let push_to_new_remote vcs ~repo_root ~prefix =
  let remote_root = create_bare_remote vcs ~prefix in
  Vcs.git
    vcs
    ~repo_root
    ~args:[ "remote"; "add"; "origin"; Vcs.Repo_root.to_string remote_root ]
    ~f:Vcs.Git.exit0;
  Vcs.git
    vcs
    ~repo_root
    ~args:[ "push"; "--set-upstream"; "origin"; "main" ]
    ~f:Vcs.Git.exit0;
  remote_root
;;

let create_fake_subrepo vcs ~subrepo =
  let repo_root = init_repo vcs ~prefix:(Central.Subrepo.to_string subrepo) in
  let readme = Vcs.Path_in_repo.v "README.md" in
  write_file ~repo_root ~path_in_repo:readme ~contents:(fake_readme_contents subrepo);
  Vcs.add vcs ~repo_root ~path:readme;
  let initial_rev =
    commit_and_ensure_main_branch vcs ~repo_root ~commit_message:"Initial commit"
  in
  Vcs.git vcs ~repo_root ~args:[ "branch"; "subrepo" ] ~f:Vcs.Git.exit0;
  let remote_root =
    push_to_new_remote vcs ~repo_root ~prefix:(Central.Subrepo.to_string subrepo)
  in
  { Fake_subrepo.subrepo; repo_root; remote_root; initial_rev }
;;

(* Adds a commit to the (already created) central repo that introduces
   [repo/<name>/README.md] and [repo/<name>/.gitrepo], exactly as if the
   subrepo had just been set up - the commit's own parent is used as
   [.gitrepo]'s [parent] field, matching the invariant relied upon by
   [Subrepo_facts.compute] to locate the base revision of a subrepo. *)
let add_fake_subrepo_to_central vcs ~central_root (fake_subrepo : Fake_subrepo.t) =
  let { Fake_subrepo.subrepo; repo_root; remote_root = _; initial_rev } = fake_subrepo in
  let readme_path =
    Vcs.Path_in_repo.v
      (Filename.concat
         (Vcs.Path_in_repo.to_string (Central.Subrepo.root subrepo))
         "README.md")
  in
  write_file
    ~repo_root:central_root
    ~path_in_repo:readme_path
    ~contents:(fake_readme_contents subrepo);
  Vcs.add vcs ~repo_root:central_root ~path:readme_path;
  (* [parent_rev] is captured here, before README.md/[.gitrepo] are committed
     below - so it points at a central revision where those files don't
     exist yet. [Subrepo_facts.compute] doesn't diff from [parent_rev]
     directly, it searches for the child commit whose own [.gitrepo] records
     this exact [parent_rev] - which here is precisely the "Add fake
     subrepo" commit below, the one that *does* already contain these files.
     So this does not create a spurious outgoing diff at the moment
     [create] returns. *)
  let parent_rev = Vcs.current_revision vcs ~repo_root:central_root in
  let gitrepo_path = Central.Subrepo.gitrepo_file_path subrepo in
  let gitrepo_contents =
    Gitrepo_file.create
      ~remote:(`Repo_root repo_root)
      ~branch:(Vcs.Branch_name.v "subrepo")
      ~commit:initial_rev
      ~parent:parent_rev
      ()
    |> Gitrepo_file.write
  in
  write_file ~repo_root:central_root ~path_in_repo:gitrepo_path ~contents:gitrepo_contents;
  Vcs.add vcs ~repo_root:central_root ~path:gitrepo_path;
  let (_ : Vcs.Rev.t) =
    Vcs.commit
      vcs
      ~repo_root:central_root
      ~commit_message:
        (Vcs.Commit_message.v
           (Printf.sprintf "Add fake subrepo %s" (Central.Subrepo.to_string subrepo)))
  in
  ()
;;

let create ~vcs ~subrepos =
  let central_root = init_repo vcs ~prefix:"central" in
  let readme = Vcs.Path_in_repo.v "README.md" in
  write_file
    ~repo_root:central_root
    ~path_in_repo:readme
    ~contents:"# central\n\nA fake central repo, generated by [Central_test_helpers].\n";
  Vcs.add vcs ~repo_root:central_root ~path:readme;
  let (_ : Vcs.Rev.t) =
    commit_and_ensure_main_branch
      vcs
      ~repo_root:central_root
      ~commit_message:"Initial commit"
  in
  let fake_subrepos =
    List.map subrepos ~f:(fun subrepo ->
      let fake_subrepo = create_fake_subrepo vcs ~subrepo in
      add_fake_subrepo_to_central vcs ~central_root fake_subrepo;
      fake_subrepo)
  in
  (* Central's remote is only pushed to now, once every subrepo's scaffolding
     commit has landed - so a freshly [create]d repo looks like a checkout
     that is fully up to date with its remote, not one sitting on unpushed
     commits. *)
  let central_remote_root =
    push_to_new_remote vcs ~repo_root:central_root ~prefix:"central"
  in
  { Fake_central.central_root; central_remote_root; subrepos = fake_subrepos }
;;
